### ISSUE TITLE
The command '/bin/sh -c apk --no-cache add dnsmasq=2.85-r1' returned a non-zero code: 1

### ISSUE THREAD

**Issue by patsevanton** [brav0charlie/docker-dnsmasq#1]
```
docker-compose up -d
Creating network "dnsmasq" with the default driver
Building dnsmasq
Sending build context to Docker daemon  2.048kB
Step 1/8 : FROM alpine:edge
edge: Pulling from library/alpine
fa7045767063: Pull complete 
Digest: sha256:a81f67aca260e41b2260a4cf91ac4435dcad62ccc108ab19ae3077aafa1a4722
Status: Downloaded newer image for alpine:edge
 ---> b0da5d0678e7
Step 2/8 : LABEL maintainer="Bill Clark <36345117+brav0charlie@users.noreply.github.com>"
 ---> Running in dcd327f8a72d
Removing intermediate container dcd327f8a72d
 ---> 2f305ccad027
Step 3/8 : LABEL github_url="https://github.com/brav0charlie/docker-dnsmasq"
 ---> Running in 923f5c719322
Removing intermediate container 923f5c719322
 ---> 1f3011bd0811
Step 4/8 : RUN apk --no-cache add dnsmasq=2.85-r1
 ---> Running in c63b77b5195c
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  dnsmasq-2.85-r2:
    breaks: world[dnsmasq=2.85-r1]
The command '/bin/sh -c apk --no-cache add dnsmasq=2.85-r1' returned a non-zero code: 1
ERROR: Service 'dnsmasq' failed to build : Build failed
```

**Comment by brav0charlie** [comment]
Thanks for filing this issue! 

Looks like the updated Docker image for Alpine Linux Edge breaks compatibility with dnsmasq v2.85-r1. 

This has been resolved in the latest commit and the latest release. I've updated the Dockerfile to pull dnsmasq v2.85-r2.

Link to updated release: [v2.85-r2](https://github.com/brav0charlie/docker-dnsmasq/releases/tag/v2.85-r2)

**Comment by brav0charlie** [comment]
Oops, didn't mean to close this issue. Please reply here if you continue to have any trouble following the update I made.

**Comment by Francois14041999** [comment]
I encountered the same problem when I'm trying to run my Dockerfile...

Here is the problem : 

Error response from daemon: The command '/bin/sh -c set -eux;   mkdir -p var/cache var/log;     composer dump-autoload --classmap-authoritative --no-dev;   composer dump-env prod;  composer run-script --no-dev post-install-cmd;  chmod +x bin/console; sync' returned a non-zero code: 1
Failed to deploy '<unknown> Dockerfile: api/Dockerfile': Can't retrieve image ID from build stream"

And here is the part of my Dockerfile which is responsible of this problem following the error message :

 RUN set -eux; \
	mkdir -p var/cache var/log; \
	composer dump-autoload --classmap-authoritative --no-dev; \
	composer dump-env prod; \
	composer run-script --no-dev post-install-cmd; \
	chmod +x bin/console; sync
VOLUME /srv/api/var

I don't know how to solve it, I'm open to any idea !!

**Comment by Francois14041999** [comment]
After days of research I've found the origin of the problem...it's simply a path initially present with the files which was responsible of the error !

**Comment by brav0charlie** [comment]
Apologies for the delayed response, but I'm happy to hear you've got it worked out! :)

I'll mark this as closed.
